### GENERAL SETTINGS ###

# Site settings
title: Ian Hudson
description: "My name is Ian Hudson and I am a Programmer at Sumo Digital Nottingham."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://ianmhudson.com/"

homeImage: 

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hi, my name is Ian Hudson and I am a Programmer at Sumo Digital Nottingham. I have passion for learning new skills and gaining knowledge. I love to see what could be created and what has been created in the video games industry and hope to be able to contribute in creating or expanding a universe which people love. <br><br> I would love to chat about job opportunities, projects that I've worked on, anything gaming related even my interest in sports (Skiing and Badminton)."

aboutFooter: "Programmer at Sumo Digital Nottingham."


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" #00b3fe
  primary_rgb: "0, 79,254" #"247,0,49" #0,179,254 #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D" #384452
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  background: "#FFFFFF"
  text_color: "#000000"
  update_text_title: "#FFFFFF"
font_size: 16px

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/
  personalProjects:
    output: true
    permalink: /personalProjects/:title/
    
Tags:
 C++: "#00b3fe"
 
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/I-Hudson
  - title: twitter
    url: https://twitter.com/IanHudsonDev
  - title: linkedin
    url: https://www.linkedin.com/in/ian-hudson/

# Contact email and phone number
email: ianm.hud@gmail.com
    
