### GENERAL SETTINGS ###

# Site settings
title: Ian Hudson
description: "My name is Ian Hudson and I am a Computer Games Programming student at the University of Gloucestershire."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://ianmhudson.com/"

homeImage: 

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hi, my name is Ian Hudson and I am a Computer Games Programming student at the University of Gloucestershire currently in my last year. Here you can see projects that I have worked on. If you would like to see my personal projects, please head over to my GitHub (Link at the bottom of the page). I have passion for leaning new skills and gaining knowledge. I love to see what could be created and have has been in the video games industry and hope to be able to contribute in creating or expanding an universe which people love. <br><br> I would love to chat about job opportunities, projects that I've worked on, anything gaming related even my interest for sport (Skiing and Badminton)."

aboutFooter: 


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" #00b3fe
  primary_rgb: "0, 79,254" #"247,0,49" #0,179,254 #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D" #384452
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  background: "#FFFFFF"
  text_color: "#000000"
  update_text_title: "#FFFFFF"
font_size: 16px

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/
  personalProjects:
    output: true
    permalink: /personalProjects/:title/
    

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/I-Hudson
  - title: twitter
    url:

# Contact email and phone number
email: ianm.hud@gmail.com
mobile: Mobile on request
    
